Fix main branch ResumeStrategyConfiguration - revert requirements for non null resume cache
it was introduced by https://github.com/apache/camel/pull/23021

and causing for instance:
```
org.apache.camel.FailedToCreateRouteException: Failed to create route:
route1 at: >>> org.apache.camel.model.ResumableDefinition@376498da <<<
in route: Route(route1)[From[aws2-kinesis://ckc-kin-stream-cons-52?ama...
because: java.lang.reflect.InvocationTargetException
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:248)
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:89)
	at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
	at org.apache.camel.impl.DefaultCamelContext.lambda$doStartRouteDefinitions$3(DefaultCamelContext.java:770)
	at org.apache.camel.util.concurrent.ContextValueFactory.lambda$where$0(ContextValueFactory.java:82)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:65)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:81)
	at org.apache.camel.util.concurrent.ContextValue.where(ContextValue.java:186)
	at org.apache.camel.impl.engine.DefaultCamelContextExtension.createRoute(DefaultCamelContextExtension.java:434)
	at org.apache.camel.impl.DefaultCamelContext.doStartRouteDefinitions(DefaultCamelContext.java:768)
	at org.apache.camel.impl.DefaultCamelContext.lambda$startRouteDefinitions$0(DefaultCamelContext.java:641)
	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$startingRoutes$2(AbstractCamelContext.java:1159)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:65)
	at org.apache.camel.util.concurrent.ContextValue.where(ContextValue.java:174)
	at org.apache.camel.impl.engine.AbstractCamelContext.startingRoutes(AbstractCamelContext.java:1157)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:640)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:622)
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2701)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:94)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2312)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:124)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2331)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:214)
	at org.apache.camel.test.junit6.util.CamelContextTestHelper.startCamelContext(CamelContextTestHelper.java:236)
	at org.apache.camel.test.junit6.util.CamelContextTestHelper.startCamelContextOrService(CamelContextTestHelper.java:254)
	at org.apache.camel.test.junit6.TransientCamelContextManager.tryStartCamelContext(TransientCamelContextManager.java:180)
	at org.apache.camel.test.junit6.TransientCamelContextManager.initialize(TransientCamelContextManager.java:131)
	at org.apache.camel.test.junit6.TransientCamelContextManager.createCamelContext(TransientCamelContextManager.java:66)
	at org.apache.camel.test.junit6.CamelTestSupport.setUp(CamelTestSupport.java:150)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.apache.camel.RuntimeCamelException:
java.lang.reflect.InvocationTargetException
	at org.apache.camel.support.ObjectHelper.newInstance(ObjectHelper.java:539)
	at org.apache.camel.impl.engine.DefaultInjector.newInstance(DefaultInjector.java:77)
	at org.apache.camel.support.ResolverHelper.doResolveService(ResolverHelper.java:283)
	at org.apache.camel.support.ResolverHelper.resolveMandatoryService(ResolverHelper.java:200)
	at org.apache.camel.support.ResolverHelper.resolveMandatoryBootstrapService(ResolverHelper.java:182)
	at org.apache.camel.reifier.ResumableReifier.resolveResumeStrategy(ResumableReifier.java:65)
	at org.apache.camel.reifier.ResumableReifier.createProcessor(ResumableReifier.java:41)
	at org.apache.camel.reifier.ProcessorReifier.lambda$makeProcessor$1(ProcessorReifier.java:851)
	at org.apache.camel.impl.engine.DefaultCamelContextExtension.lambda$createProcessor$1(DefaultCamelContextExtension.java:469)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:65)
	at org.apache.camel.util.concurrent.ContextValue.where(ContextValue.java:174)
	at org.apache.camel.impl.engine.DefaultCamelContextExtension.createProcessor(DefaultCamelContextExtension.java:467)
	at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:837)
	at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:618)
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:240)
	... 31 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.apache.camel.support.ObjectHelper.newInstance(ObjectHelper.java:537)
	... 45 more
Caused by: java.lang.NullPointerException: resumeCache
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at org.apache.camel.resume.ResumeStrategyConfiguration.setResumeCache(ResumeStrategyConfiguration.java:66)
	at org.apache.camel.component.aws2.kinesis.consumer.KinesisResumeStrategyConfiguration$KinesisResumeStrategyConfigurationBuilder.build(KinesisResumeStrategyConfiguration.java:63)
	at org.apache.camel.component.aws2.kinesis.consumer.KinesisResumeStrategy.<init>(KinesisResumeStrategy.java:34)
	... 48 more
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>