CAMEL-18021: camel-debezium - Support default value for lists (#7506)
## Motivation

For now it is not possible to upgrade Debezium to 1.9 because `PostgresConnectorConfig` has a default value for a type list that is not properly supported by the maven plugin such that we end up with compilation error of the following type:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /camel/components/camel-debezium/camel-debezium-postgres/src/generated/java/org/apache/camel/component/debezium/configuration/PostgresConnectorEmbeddedDebeziumConfiguration.java:[97,39] error: illegal start of expression
[ERROR] /camel/camel/components/camel-debezium/camel-debezium-postgres/src/generated/java/org/apache/camel/component/debezium/configuration/PostgresConnectorEmbeddedDebeziumConfiguration.java:[97,41] error: <identifier> expected
[INFO] 2 errors 
```

## Modifications

* Propose a new method called `getDefaultValueAsStringLiteral` to provide the default value as a `String` literal to be used to set the default value in the annotation `UriParam` which relies on the method `ConfigDef.convertToString` to convert the list as String.
* Simplify the method `getDefaultValueWrappedInString` by relying on the method `ConfigDef.convertToString` for list and class
* Fix the default value set in the annotation `UriParam` in case of a class (only the name of the class is expected)
* Fix typos in "overridden" (not related to the initial issue)