Avoid potential NPE when the kafka consumer failed to start
to avoid this kind of NPE:
```
java.lang.NullPointerException: Cannot invoke
"org.apache.kafka.clients.consumer.Consumer.wakeup()" because
"this.consumer" is null
	at org.apache.camel.processor.resume.kafka.SingleNodeKafkaResumeStrategy.stop(SingleNodeKafkaResumeStrategy.java:412)
	at org.apache.camel.processor.resume.ResumableProcessor.doStop(ResumableProcessor.java:75)
	at org.apache.camel.support.service.BaseService.stop(BaseService.java:167)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:201)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:185)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:170)
	at org.apache.camel.impl.engine.DefaultChannel.doStop(DefaultChannel.java:138)
	at org.apache.camel.support.service.BaseService.stop(BaseService.java:167)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:201)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:185)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:216)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:187)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:170)
	at org.apache.camel.processor.Pipeline.doStop(Pipeline.java:209)
	at org.apache.camel.support.service.BaseService.stop(BaseService.java:167)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:201)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:185)
	at org.apache.camel.support.processor.DelegateAsyncProcessor.doStop(DelegateAsyncProcessor.java:107)
	at org.apache.camel.support.service.BaseService.stop(BaseService.java:167)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:201)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:185)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:170)
	at org.apache.camel.support.DefaultConsumer.doStop(DefaultConsumer.java:236)
	at org.apache.camel.component.kafka.KafkaConsumer.doStop(KafkaConsumer.java:225)
	at org.apache.camel.support.service.BaseService.stop(BaseService.java:167)
	at org.apache.camel.support.service.ServiceHelper.stopService(ServiceHelper.java:201)
	at org.apache.camel.impl.engine.DefaultShutdownStrategy.shutdownNow(DefaultShutdownStrategy.java:434)
	at org.apache.camel.impl.engine.DefaultShutdownStrategy$ShutdownTask.run(DefaultShutdownStrategy.java:743)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>