Reduce SpringQuartzPersistentStoreRestartAppChangeOptionsTest.testRestartAppChangeTriggerOptions flakiness
in case of one first flaky failure, the next 2 runs were failing due to
conflicting JMX ObjectName MBean because the application was not
correctly closed

```
org.apache.camel.RuntimeCamelException:
org.apache.camel.VetoCamelContextStartException: CamelContext
(camelContext-SpringQuartzPersistentStoreRestartAppChangeOptionsTest)
with ObjectName[org.apache.camel:context=camelContext-SpringQuartzPersistentStoreRestartAppChangeOptionsTest,type=context,name="camelContext-SpringQuartzPersistentStoreRestartAppChangeOptionsTest"]
is already registered. Make sure to use unique names on CamelContext
when using multiple CamelContexts in the same MBeanServer.
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>