Revert "CAMEL-25044: camel-core - ExpressionBuilder and PredicateBuilder: fix bugs found in a deep review (#26924)"
This reverts commit 1dd20e7560400ac6a9da2011bbb2161b4dded31e.

it is causing errors:

```
org.opentest4j.AssertionFailedError: should name the variable source,
not the body, but was: No 'input' variable available. Exchange[] ==>
expected: <true> but was: <false>
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:232)
	at org.apache.camel.jsonpath.JsonPathNullBodyHintTest.testNullVariableSourceNamesTheSource(JsonPathNullBodyHintTest.java:67)
```

```
org.opentest4j.AssertionFailedError: should name the variable source,
not the body, but was: No 'input' variable available. Exchange[] ==>
expected: <true> but was: <false>
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:232)
	at org.apache.camel.language.jq.JqNullBodyHintTest.testNullVariableSourceNamesTheSource(JqNullBodyHintTest.java:69)
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>