Skip unit test for DuckDb on ppc64le and s390x
the integration tests were already skipped.

it is failing with:

```
Caused by: java.lang.ExceptionInInitializerError: Exception
java.lang.IllegalStateException: Unsupported system architecture [in
thread "main"]
	at org.duckdb.DuckDBNative.<clinit>(DuckDBNative.java:36)
	at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:58)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:117)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:191)
	at org.apache.camel.component.duckdb.DuckDbEndpoint.doStart(DuckDbEndpoint.java:136)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:132)
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>