CAMEL-24812 - exclude camel-salesforce-maven-plugin from modules to build
camel-salesforce-maven-plugin-it is a module not part of the reactor, it
is a module used as an IT tests so the incremental build should not try
to build it.
it was causing this kind of error:

```
[ERROR] Could not find the selected project in the reactor:
:camel-salesforce-maven-plugin-it -> [Help 1]
  org.apache.maven.MavenExecutionException: Could not find the selected
project in the reactor: :camel-salesforce-maven-plugin-it
```

ideally, it should detect that it is inside the it test and trigger
build of parent but the script is currently not in a place for this kind
of thing so excluding the parent module and marking it as requiring to
be built manually

co-authored-by: IBM Bob 2.0.3
Signed-off-by: Aurélien Pupier <apupier@ibm.com>