CAMEL-22463 - Add jackson dependency to hashicorp vault
the jackson dependency is now optional with spring-vault-core 4.x
This is needed by this component, otherwise there is this kind of error:

```
Caused by: java.lang.ExceptionInInitializerError: Exception
java.lang.IllegalStateException: Either Jackson 2 or Jackson 3 must be
available on the classpath [in thread "main"]
	at org.springframework.vault.support.JacksonCompat.<clinit>(JacksonCompat.java:97)
	at org.springframework.vault.client.VaultClients.createRestTemplate(VaultClients.java:152)
	at org.springframework.vault.client.VaultClients.createRestTemplate(VaultClients.java:90)
	at org.springframework.vault.client.RestTemplateBuilder.createTemplate(RestTemplateBuilder.java:251)
	at org.springframework.vault.client.RestTemplateBuilder.build(RestTemplateBuilder.java:227)
	at org.springframework.vault.core.VaultTemplate.doCreateRestTemplate(VaultTemplate.java:336)
	at org.springframework.vault.core.VaultTemplate.<init>(VaultTemplate.java:114)
	at org.apache.camel.component.hashicorp.vault.integration.HashicorpVaultPropertiesSourceNoEnvTestIT.init(HashicorpVaultPropertiesSourceNoEnvTestIT.java:58)
```

it is a similar solution than used for pqc:
https://github.com/apache/camel/commit/73ea276e3666c81b18fe559a69cbfc4fb37685a6

Signed-off-by: Aurélien Pupier <apupier@ibm.com>