camel-core - Optimize as the lambda code causes JVM compiler internally to throw an java.lang.NoSuchMethodError when it compiles the lambda code. JDK mission control reports this.