CAMEL-18560: camel-etcd3 - Align the grpc version of jetcd-grpc with vertx-grpc (#8445)
## Motivation

Merging https://github.com/apache/camel/pull/8436 causes a build failure in camel-spring-boot project with an error or type:
```
[INFO] --- camel-spring-boot-generator-maven-plugin:3.19.0-SNAPSHOT:prepare-spring-boot-starter (generate) @ camel-etcd3-starter ---
org.apache.maven.artifact.versioning.OverConstrainedVersionException: The artifact has no valid ranges
  io.grpc:grpc-core:jar:1.47.0

Path to dependency: 
	1) org.apache.camel:camel-etcd3:pom:3.19.0-SNAPSHOT
	2) io.etcd:jetcd-core:jar:0.7.3
	3) io.etcd:jetcd-grpc:jar:0.7.3
```

## Modifications

This is due to a conflict of grpc version used by jetcd-grpc (1.48.0) and the one used by vertx-grpc (1.47.0).

* Align the grpc versions to `1.47.0`
* Exclude grpc from jetcd-core