Avoid flakiness of CxfTimeoutTest
as we can see here
https://develocity.apache.org/scans/tests?search.rootProjectNames=camel&search.timeZoneId=Europe%2FParis&tests.container=org.apache.camel.component.cxf.CxfTimeoutTest
, this test is flaky.
it also sometimes cannot even be initialized with
```
jakarta.xml.ws.WebServiceException:
org.apache.cxf.endpoint.ListenerRegistrationException: Soap 1.1 endpoint
already registered on address
http://localhost:29753/CxfTimeoutTest/SoapContext/SoapPort
	at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:373)
	at org.apache.cxf.jaxws.EndpointImpl.publish(EndpointImpl.java:255)
	at org.apache.cxf.jaxws.spi.ProviderImpl.createAndPublishEndpoint(ProviderImpl.java:130)
	at jakarta.xml.ws.Endpoint.publish(Endpoint.java:224)
	at org.apache.camel.component.cxf.CxfTimeoutTest.startService(CxfTimeoutTest.java:57)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.apache.cxf.endpoint.ListenerRegistrationException: Soap
1.1 endpoint already registered on address
http://localhost:29753/CxfTimeoutTest/SoapContext/SoapPort
	at org.apache.cxf.binding.soap.SoapBindingFactory.addListener(SoapBindingFactory.java:923)
	at org.apache.cxf.endpoint.ServerImpl.start(ServerImpl.java:130)
	at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:364)
	... 6 more
```

Attempt to enforce this test to play in isolation to avoid side effect

Signed-off-by: Aurélien Pupier <apupier@ibm.com>