Revert "CAMEL-24973: camel-util - Align URISupport.sanitizeUri with the endpoint URI parser (#26803)"
This reverts commit 84f265e8d1b3548fd03f0fd0474cf6c410e5e9e6.

it is causing several grpc tests to fail with this kind of error:

```
org.apache.camel.FailedToCreateRouteException: Failed to create route:
grpc-async (source: ContextValueFactory.java):
Route(grpc-async)[From[grpc://localhost:0/org.apache.camel.c... because:
Failed to resolve endpoint:
grpc://localhost:0/org.apache.camel.component.grpc.PingPong?consumerStrategy=AGGREGATION&hash=1&synchronous=true
due to: Failed to resolve endpoint:
grpc://localhost:0/org.apache.camel.component.grpc.PingPong?consumerStrategy=AGGREGATION&hash=1&synchronous=true
due to: There are 1 parameters that couldn't be set on the endpoint.
Check the uri if the parameters are spelt correctly and that they are
properties of the endpoint. Unknown parameters=[{hash=1}]
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>