Fix DuckDbProducerIT test
the regression was introduced by
https://github.com/apache/camel/commit/bb6882f9f2f041015227f874fb4b51910d09ee9c

an encapsulation was created thus the instanceof check was not working
anymore

the error message was:

```
org.apache.camel.CamelExecutionException: Exception occurred during
execution on the exchange: Exchange[E0AFAC2934D1620-0000000000000000]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:60)
	at org.apache.camel.support.ExchangeHelper.extractResultBody(ExchangeHelper.java:704)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:594)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:590)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:188)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:194)
	at org.apache.camel.component.duckdb.integration.DuckDbProducerIT.insertAndQueryRoundTrip(DuckDbProducerIT.java:77)
Caused by: java.sql.SQLException: Catalog Error: Table with name
camel_events does not exist!
Did you mean "pg_class"?
	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:155)
	at org.duckdb.DuckDBPreparedStatement.<init>(DuckDBPreparedStatement.java:90)
	at org.duckdb.DuckDBConnection.prepareStatement(DuckDBConnection.java:121)
	at org.duckdb.DuckDBConnection.prepareStatement(DuckDBConnection.java:306)
	at org.apache.camel.component.duckdb.DuckDbInsertSupport.insertMaps(DuckDbInsertSupport.java:47)
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>