Improve test assertion for org.apache.camel.dsl.jbang.core.commands.tui.ConsumersTabRenderTest.renderShowsTableHeaders()
it gives:

```
org.apache.camel.dsl.jbang.core.commands.tui.ConsumersTabRenderTest.renderShowsTableHeaders
-- Time elapsed: 0.004 s <<< FAILURE!
java.lang.AssertionError:
[Should show ROUTE, STATUS, TYPE and URI headers]
Expecting actual:
  "╭ Consumers
───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│    ROUTE▼              STATUS     TYPE       REMOTE   INFLIGHT
SCHEDULE                 POLLS SINCE-LAST             │
│    route1              Started    Timer                      0
-/-/-                  │
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
"
to contain:
  ["ROUTE", "STATUS", "TYPE", "URI"]
but could not find:
  ["URI"]

	at org.apache.camel.dsl.jbang.core.commands.tui.ConsumersTabRenderTest.renderShowsTableHeaders(ConsumersTabRenderTest.java:66)
```

instead of:

```
[camel-jbang-plugin-tui] [ERROR] Tests run: 1, Failures: 1, Errors: 0,
Skipped: 0, Time elapsed: 0.009 s <<< FAILURE! -- in
org.apache.camel.dsl.jbang.core.commands.tui.ConsumersTabRenderTest
[camel-jbang-plugin-tui] [ERROR]
org.apache.camel.dsl.jbang.core.commands.tui.ConsumersTabRenderTest.renderShowsTableHeaders
-- Time elapsed: 0.008 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Should show URI header ==>
expected: <true> but was: <false>
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:232)
	at org.apache.camel.dsl.jbang.core.commands.tui.ConsumersTabRenderTest.renderShowsTableHeaders(ConsumersTabRenderTest.java:67)
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>