camel-elasticsearch: Downgrade the jackson version to 2.14.3 (#10203)
## Motivation

The integration tests of the component `camel-elasticsearch` fail due to a `NoClassDefFoundError: com/fasterxml/jackson/core/StreamReadConstraints`, this class has actually a different package name in Jackson 2.15.

## Modifications:

* Downgrade the version of Jackson specifically for the component `camel-elasticsearch` until a version of `elasticsearch-java` supports Jackson 2.15.